### ISSUE TITLE
Bug: Wish URL overwritten to bad URL after extraction

### ISSUE THREAD

**Issue by tpansino** [cmintey/wishlist#124]
**Describe the bug**

When attempting to add certain item URLs the URL is overwritten after extraction runs, causing the URL to be invalid. There doesn't appear to be a way to fix the URL after this happens either.

**To Reproduce**

1. Open the dialog to add a new item to a wishlist
2. Enter the URL https://www.rei.com/gift-card/purchase
3. Observe extraction runs and the URL is changed to `https://www.rei.com/null`
4. Attempt to change the URL back to `https://www.rei.com/gift-card/purchase`, observe extraction runs again and it is reset back to `https://www.rei.com/null`

**Expected behavior**

1. The URL after extraction shouldn't have a `null` in it - I'm guessing that's an unset variable that failed to extract properly because of the site
2. The URL should (IMO) "stick" the second time it's set, and not attempt to rerun extraction on the page. (If you want to preserve the ability to re-run the extraction logic, maybe add a refresh button/icon to the right of the Item URL text box for that?)

**Screenshots**

![Screenshot 2024-07-23 at 10 40 20](https://github.com/user-attachments/assets/c8c86d7c-25f1-4d6e-95cb-3cb4aa8f3eab)

**Desktop (please complete the following information):**
 - OS: MacOS 14.5
 - Browser: Firefox 128.0

**Comment by cmintey** [comment]
Interesting. We try to resolve the url by using some opengraph properties when possible. In this case, it seems the issue actually lies on REI's website. I don't know how common this is, but I agree, there should be a way to override this
![image](https://github.com/user-attachments/assets/97993d94-4a4d-4458-a46d-158c27b0d47c)

**Comment by tpansino** [comment]
Oh interesting. I'll try to send them a support ticket for that, just to try to fix it on both sides.

**Comment by tpansino** [comment]
The fix works great, thanks @cmintey for all your hard work. 🏆
