### ISSUE TITLE
Bug: 403 on initial wizard setup

### ISSUE THREAD

**Issue by Asgoret** [cmintey/wishlist#137]
Initial admin doesn't created on v0.32.2.

1. Delete all files, storages and docker network.
2. Run docker compose from readme
3. Go through wizard setup
4. Look at 403 in console

UPD: Response `{"message":"Cross-site POST form submissions are forbidden"}`

![image](https://github.com/user-attachments/assets/7348a610-108a-4fd0-b8a9-671689ab8fd0)

**Comment by cmintey** [comment]
Hi there. I'm not able to reproduce. Is the `ORIGIN` value set in the .env file? If you're on localhost for testing, then it should be `ORIGIN=http://localhost:3280`

**Comment by Asgoret** [comment]
U where right! Thanks

**Comment by schmurtzm** [comment]
Note that if you have this message one time, after that the data are corrupted: even modifying ORIGIN value is not enough, you have to drop the data of the docker and make a fresh install.

A detail: when pressing "Next" the button spinner is always spinning forever (even when the server answer is finished).
