### ISSUE TITLE
Feature: Shareable public wishlist view

### ISSUE THREAD

**Issue by andrewgioia** [cmintey/wishlist#140]
**Is your feature request related to a problem? Please describe.**
Currently there's no way to share a wishlist with someone without them also having an account. Sharing a Christmas list with family, for instance, requires all family members to register first just to see the items.

**Describe the solution you'd like**
Having a public URL for a list would enable linking to it in view-only mode (or perhaps even allowing for claiming an item). Most registry and gift list websites allow for this without requiring gift givers to also register.

**Describe alternatives you've considered**
An alternative would be a password protected public view so that the page isn't completely exposed.

**Additional context**
Love the app! Amazing work, would love this feature added 🙏

**Comment by cmintey** [comment]
Hi! Thanks for the request and feedback. This feature actually already is available as of a few versions ago. It's under the group settings called "Wishlist Mode", you can set this value to be "Registry" and it will act as you described.

The limitations with this is that there is only a single list and you cannot switch your group if it already has multiple users in it.

Let me know if this is what you're after!

**Comment by andrewgioia** [comment]
Awesome! Yes this is the exact functionality I was looking for 🎉  Apologies, I didn't see anything when going through my instance/readme.

Thanks so much for the great app!
