### ISSUE TITLE
Feature: Anonymous claiming of wishes

### ISSUE THREAD

**Issue by mztiq** [cmintey/wishlist#150]
**Is your feature request related to a problem? Please describe.**
We always keep the whole gifting process (who is partnered with whom) a secret until Christmas Eve.
Right now when you claim a wish off of a wishlist it shows the user who claimed it.

**Describe the solution you'd like**
Having the option to stay anonymous while claiming wishes would be great.

**Comment by cmintey** [comment]
Hi there, this feature exists. Under your group settings you can uncheck the box called "Show name" in the Claims sub-setting. It'll hide the names of who claimed what

**Comment by mztiq** [comment]
Thanks for the clarification, I somehow overlooked that option.
