### ISSUE TITLE
Feature: Change currency

### ISSUE THREAD

**Issue by Akirainblack** [cmintey/wishlist#152]
**Is your feature request related to a problem? Please describe.**
I live in the U.K. we use £ not $

**Describe the solution you'd like**
The ability to specify using £ not $

**Describe alternatives you've considered**
Specifying location and the system would then update to the correct currency.

**Comment by cmintey** [comment]
Hi, you can change the currency per item like below. You can also globally change the currency by setting the `DEFAULT_CURRENCY` environment variable.

![image](https://github.com/user-attachments/assets/7136de66-0c66-42d8-9685-4115a7501060)

**Comment by Akirainblack** [comment]
Thank you, sorry didn't see that the DEFAULT_CURRENCY variable existed. Or how to change it.
Will you be adding that to the documentation?

**Comment by cmintey** [comment]
Yes definitely, I will add it to documentation!

**Comment by Pr0mises** [comment]
Also please add screenshots, I was in hurry as christmas and birthdays are coming up so I've chosen another wishlist program. After seeing that screenshot I have to check your program aswell, even tho the other is in use and maybe convert everything to your app. Just of the looks of your app in that one screenshot

**Comment by cmintey** [comment]
Added a new environment variables section and images to the readme
