### ISSUE TITLE
Bug: Invite User from Group Admin Page Fails

### ISSUE THREAD

**Issue by sugarfunk** [cmintey/wishlist#153]
**Describe the bug**
If you go to a group page from admin, then try to Invite a user, the invite does nothing and logs throw error

**To Reproduce**
1. Go to Admin
2. Click on group
3. click non-default group
4. click Invite User

**Expected behavior**
Pop-up asking for email address

**Screenshots**
![image](https://github.com/user-attachments/assets/6eff6a73-7d75-4612-be23-0c56d6a3e000)

**Additional context**
Error Logs...
`
wishlist  | Listening on 0.0.0.0:3000
wishlist  | SvelteKitError: Not found: /admin/groups/93965a1c-c9e4-44ce-9564-63c0915ef469/sw.js
wishlist  |     at resolve2 (file:///usr/src/app/build/server/index.js:3765:18)
wishlist  |     at resolve (file:///usr/src/app/build/server/index.js:3598:34)
wishlist  |     at Object.handle (file:///usr/src/app/build/server/chunks/hooks.server-JFPpgpwF.js:32:10)
wishlist  |     at async respond (file:///usr/src/app/build/server/index.js:3596:22)
wishlist  |     at async Array.ssr (file:///usr/src/app/build/handler.js:1272:3) {
wishlist  |   status: 404,
wishlist  |   text: 'Not Found'
wishlist  | }
`

**Comment by cmintey** [comment]
Thanks for reporting this. Does inviting from the main admin page still work? You can specify the group there as well

**Comment by sugarfunk** [comment]
Main page works fine, just. Seems to only be an issue within the specific group pages.

**Comment by sugarfunk** [comment]
Can confirm fix from #155. Thanks!! Great work with this project.
