### ISSUE TITLE
Feature: Translation

### ISSUE THREAD

**Issue by nkgiovannivl** [cmintey/wishlist#166]
**Is your feature request related to a problem? Please describe.**
I wanna collaborate to Spanish translation.

**Describe the solution you'd like**
Allow to collaborate with translations to other languages.

**Additional context**
I really like this whishlist, easy docker compose, pc browser and cell phone browser looks really good! And reverse proxy usage without any complicated configuration!,  Thanks!

**Comment by cmintey** [comment]
Thanks! This is definitely something I want to set up at some point

**Comment by Thulkash** [comment]
I'd love to help with the French translation!

**Comment by cmintey** [comment]
Hey! I've finished adding support for translations. Translations will be managed through [Weblate](https://hosted.weblate.org/projects/wishlist/wishlist-web/). You can create an account or log in with Github to start translating. So far I've added Spanish, French, and Swedish. If there is another language you can/wish to contribute to, then you can request it through Weblate [here](https://hosted.weblate.org/new-lang/wishlist/wishlist-web/), and I'll get it added

**Comment by Luensche** [comment]
I wanted to request german, but the link does not work. No public project found.

**Comment by cmintey** [comment]
Thanks for the report. I'm looking into the Weblate access. In the meantime, I will add German, thanks!

**Comment by cmintey** [comment]
The link should work now and the project should be public. Please let me know if there are any other issues!
