### ISSUE TITLE
Bug: 502 on full refresh due to large Link header

### ISSUE THREAD

**Issue by The0mikkel** [cmintey/wishlist#170]
**Describe the bug**

When reloading the page (when behind a reverse proxy, don't know if this impacts), when on a specific wishlist, a 502 (bad gateway) is returned.  This indicates the applications fails responding.  
Log says "Broken pipe"

Besides this reload, the page works perfectly. With data automatically appearing when added.

**To Reproduce**
1. Setup system behind nginx proxy
2. Go into a wishlist
3. Reload page
4. See 502 error

**Expected behavior**

That the page can correctly be viewed, without an error (for example linking purpose)

**Logs**

Anonymized logs:
```
wishlist  | {"level":"error","ts":1732270814.374404,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","upstream":":3000","duration":137.194354435,"request":{"remote_ip":"172.18.0.22","remote_port":"59410","client_ip":"172.18.0.22","proto":"HTTP/1.1","method":"GET","host":"<domain>","uri":"/wishlists/<username>/events","headers":{"X-Forwarded-Proto":["http"],"User-Agent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"],"Sec-Fetch-Site":["same-origin"],"Cookie":["REDACTED"],"X-Real-Ip":["<server-public-ip>","<server-public-ip>"],"X-Forwarded-Host":["<domain>"],"Cache-Control":["no-cache"],"X-Forwarded-Ssl":["on"],"Sec-Fetch-Dest":["empty"],"X-Forwarded-For":["172.18.0.22"],"Accept-Encoding":["gzip, deflate, br, zstd"],"Priority":["u=1, i"],"Accept-Language":["en-US,en;q=0.8"],"Referer":["https://<domain>/wishlists/<username>"],"Accept":["text/event-stream"],"Sec-Gpc":["1"],"Sec-Ch-Ua-Platform":["\"Windows\""],"Sec-Fetch-Mode":["cors"],"X-Forwarded-Port":["443"],"Sec-Ch-Ua":["\"Brave\";v=\"131\", \"Chromium\";v=\"131\", \"Not_A Brand\";v=\"24\""],"Sec-Ch-Ua-Mobile":["?0"],"X-Original-Uri":["/wishlists/<username>/events"]}},"error":"writing: write tcp 172.18.0.32:3280->172.18.0.22:59410: write: broken pipe"}
wishlist  | {"level":"error","ts":1732270814.3744564,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","upstream":":3000","duration":83.178405594,"request":{"remote_ip":"172.18.0.22","remote_port":"59184","client_ip":"172.18.0.22","proto":"HTTP/1.1","method":"GET","host":"<domain>","uri":"/wishlists/<username>/events","headers":{"Sec-Ch-Ua-Mobile":["?0"],"X-Forwarded-Host":["<domain>"],"Sec-Ch-Ua-Platform":["\"Windows\""],"Last-Event-Id":["6"],"Sec-Fetch-Dest":["empty"],"Accept-Encoding":["gzip, deflate, br, zstd"],"Accept-Language":["da,en-US;q=0.9,en;q=0.8,de;q=0.7"],"X-Forwarded-Ssl":["on"],"User-Agent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"],"Sec-Fetch-Site":["same-origin"],"Cache-Control":["no-cache"],"Referer":["https://<domain>/wishlists/<username>"],"Priority":["u=1, i"],"Cookie":["REDACTED"],"Sec-Ch-Ua":["\"Google Chrome\";v=\"131\", \"Chromium\";v=\"131\", \"Not_A Brand\";v=\"24\""],"Dnt":["1"],"X-Original-Uri":["/wishlists/<username>/events"],"X-Forwarded-Proto":["http"],"Sec-Fetch-Mode":["cors"],"X-Real-Ip":["<client-ip>","<client-ip>"],"X-Forwarded-For":["172.18.0.22"],"X-Forwarded-Port":["443"],"Accept":["text/event-stream"]}},"error":"writing: write tcp 172.18.0.32:3280->172.18.0.22:59184: write: broken pipe"}

```

**Screenshots**

![image](https://github.com/user-attachments/assets/27539589-debf-4727-8390-7f7a05f33dd8)

Thanks for the awesome software.  
It looks and feels very nice!  
My brother just discovered this bug, and I wanted to share it.

**Comment by cmintey** [comment]
Thanks for reporting this. Is this only happening on one specific wishlist? And it's only happening after you do a full reload on that wishlist page (i.e, you're able to navigate to this list from the main page)?

**Comment by The0mikkel** [comment]
The application works as intended, besides when you do a full reload on any wishlist that i tested (3).

However `/wishlist` return 404 correctly.

**Comment by cmintey** [comment]
Hmm, I see those logs in my instance too, but it doesn't cause that error. I think that might not be the real cause. 

Can you see if there is any logs in the browser console dev tools?

**Comment by The0mikkel** [comment]
Hmm, I don't think the browser would log anything, as the response returned in the UI is from the reverse proxy. 

But I will give it a look, both into the browser logs, as well as reverse logs and maybe more logs from the software itself. 

However, that will be tomorrow

**Comment by cmintey** [comment]
Sure, if there are other relevant logs in the container or proxy, please share them

**Comment by The0mikkel** [comment]
I think I found the issue.  
It's the proxy triggers the 502 due to too big of a header

```
2024/11/23 12:37:44 [error] 2313140#2313140: *3065978 upstream sent too big header while reading response header from upstream, client: 172.18.0.1, server: <domain>, request: "GET /wishlists/alb HTTP/2.0", upstream: "http://172.18.0.32:3280/wishlists/alb", host: "<domain>"
```

The request is somehow larger when on a wishlist for some reason.

Increasing the buffer size on the proxy, did solve this: 

```nginx.conf
proxy_buffer_size   128k;
proxy_buffers   4 256k;
proxy_busy_buffers_size   256k;
```

I have quite a bit of application behind the proxy, and no other application acts like this.  
So to conclude; when requesting the individual wishlist page on page reload, it has some sort of issue with header size, which made a standard nginx-proxy fail.

My 5 cents on what it is;  
The "links" header needs to be longer due to needing to backtrack every link to the frontpage first (and maybe something else?). This adds around 361 chars longer links header - Based on my testing.   
This might send the total header size over the threshold of buffer size in my nginx proxy.

--- 

Browser logs;
After fixing the 502, I got a browser error when full-realoading wishlist pages, which is the following:

```txt
Uncaught (in promise) TypeError: Failed to register a ServiceWorker for scope ('https://<domain>/wishlists/') with script ('https://<domain>/wishlists/sw.js'): A bad HTTP response code (404) was received when fetching the script.
```

I don't get this when on the front page.

**Comment by cmintey** [comment]
Thanks for digging into that! Certainly seems like that would be the culprit, and it's a known "issue" with SvelteKit (https://github.com/sveltejs/kit/issues/11084). The header seems to help speed up app load times by telling the browser to preload certain assets like CSS. From that discussion thread, the two recommended solutions are 1) do what you have done and fix it on the proxy, or 2) update the app to not return the Link header.
Seeing as the Link header can be beneficial, I prefer option 1. I will document this on the Readme in case others run into this issue

**Comment by The0mikkel** [comment]
That's a totally valid option to go with.

Even though I of course would like not to change my Nginx settings, I believe that documenting it is a sweet spot.  
Thank you so much for the quick responses and help.

Absolutely amazing!
