### ISSUE TITLE
Feature: Default Group for self registered users

### ISSUE THREAD

**Issue by heeelga** [cmintey/wishlist#177]
I couldn't find a way to set a default group for users who are self registering.

I'd like to invite a couple of people to my wishlist but don't want to ask everyone for their email addresses. When they register on their own without an invite link they get to a page which says "Can't find your group".

I could add them to the corresponding group afterwards but it would be great to set the default group in advance.

Thanks for your work and your precious time!

**Comment by albinmedoc** [comment]
I can develop this.
@cmintey you have any specific way this should be implemented?

I come up with these various suggestions.
1. Make the first group default, cannot be changed
2. Make the first group default, can be changed later in settings
3. No group is default from the start, set in settings

**Comment by albinmedoc** [comment]
I start developing suggestion 3. So there is not much of a different from the current logic
