### ISSUE TITLE
Bug: Some translations are missing

### ISSUE THREAD

**Issue by stoni133** [cmintey/wishlist#199]
There are some missing translations:

"Password"
https://github.com/cmintey/wishlist/blob/fe02ade0c98fd42649d1490899cd6a7b9e57d6c1/src/lib/components/admin/SettingsForm/SMTP.svelte#L70
***

Default text is used for modal buttons:
https://github.com/cmintey/wishlist/blob/fe02ade0c98fd42649d1490899cd6a7b9e57d6c1/src/routes/admin/users/%5Busername%5D/%2Bpage%40.svelte#L23
https://github.com/cmintey/wishlist/blob/fe02ade0c98fd42649d1490899cd6a7b9e57d6c1/src/routes/admin/groups/%5BgroupId%5D/members/%2Bpage.svelte#L42
https://github.com/cmintey/wishlist/blob/fe02ade0c98fd42649d1490899cd6a7b9e57d6c1/src/routes/admin/groups/%5BgroupId%5D/members/%2Bpage.svelte#L58
https://github.com/cmintey/wishlist/blob/fe02ade0c98fd42649d1490899cd6a7b9e57d6c1/src/routes/admin/groups/%5BgroupId%5D/members/%2Bpage.svelte#L81
***

' is used instead of " which breaks translation
https://github.com/cmintey/wishlist/blob/fe02ade0c98fd42649d1490899cd6a7b9e57d6c1/src/routes/setup-wizard/%2Bpage.svelte#L47
https://github.com/cmintey/wishlist/blob/fe02ade0c98fd42649d1490899cd6a7b9e57d6c1/src/routes/wishlists/%5Busername%5D/%2Bpage.svelte#L192
https://github.com/cmintey/wishlist/blob/fe02ade0c98fd42649d1490899cd6a7b9e57d6c1/src/routes/wishlists/%5Busername%5D/%2Bpage.svelte#L196
***

Is it intended that Wishlist ist not translated in the wishlist mode dropdown?
https://github.com/cmintey/wishlist/blob/fe02ade0c98fd42649d1490899cd6a7b9e57d6c1/src/lib/components/admin/SettingsForm/ListMode.svelte#L19
***

All emails and their templates are not translated:
https://github.com/cmintey/wishlist/blob/fe02ade0c98fd42649d1490899cd6a7b9e57d6c1/src/lib/server/email.ts#L86
***

Just to note, the LightSwitch has an tooltip but that cannot be translated.

**Comment by cmintey** [comment]
Thanks for bringing these to my attention! If you find others, please open another issue
