### ISSUE TITLE
Feature: Change Language

### ISSUE THREAD

**Issue by nkgiovannivl** [cmintey/wishlist#200]
**Is your feature request related to a problem? 
Where need I change to Spanish after update to the lastest version?

**Describe the solution you'd like**
I was looking inside account menu on each user and check readme for ENV variable and did not found it.

Thanks!

**Comment by cmintey** [comment]
The language used is whatever language your browser is set to. There's currently no language switcher

**Comment by cmintey** [comment]
The application is also 24% translated for Spanish so far, so there are still a lot of missing translations

**Comment by nkgiovannivl** [comment]
Thanks! I'm still working on spanish translations...

**Comment by cmintey** [comment]
Thanks for helping with the translations!
