### ISSUE TITLE
Initial setup

### ISSUE THREAD

**Issue by gearopolis** [cmintey/wishlist#92]
I am interested in checking out the project and, using docker, I was able to get it up and running locally.  From there, I am not sure how to login.

The documentation doesn't refer to a default username/password.  I looked through the files and couldn't find anything else that would indicate how to login.  I did try various combinations of standard default passwords (admin/admin, admin/password, etc).

**Comment by cmintey** [comment]
Hi, thanks for your interest! On first load of the application, there should be an option at the login page to create an account. The first account that is created will be the admin account. 
Looks like this was broken a few versions ago, but it should be fixed now. Please pull the latest image once it is done building and try again

**Comment by gearopolis** [comment]
Thanks for taking a look.

I pulled the latest image and the 'create account' link was there.  I was able to get in and start exploring.

This is a great project!  I am new to using github so I am not sure if this is the right place, but I really like having the SMTP config in the admin UI and scrapping the url for an item's information is awesome.  Great interface too!  Thanks for sharing it.

**Comment by cmintey** [comment]
Glad you're up and running and thanks for the feedback!
