### ISSUE TITLE
Bug: URL scraper not getting specific item metadata from Amazon

### ISSUE THREAD

**Issue by gearopolis** [cmintey/wishlist#94]
**Describe the bug**
When adding a new item sold on Amazon.com to a wish list from my PC, the scraper is not getting the correct item name, price or image.  This does not seem to be an issue with other online shopping urls.  I also did not get this bug while adding the same item from my phone.

**To Reproduce**
1. While on computer, go to 'My Wishes' in the UI
2. Click on the 'round plus' icon in the bottom right
3. In the popup interface, paste an amazon in the top field, 'Item URL'
_I used [this](https://www.amazon.com/dp/B0894RCSV4?psc=1&ref=ppx_yo2ov_dt_b_product_details)_
4. Click out of or tab out of the field
5. See that the 'Item Name', 'Price' and 'Image URL' populate incorrectly (image is a Captcha image)

**Expected behavior**
As it does with other online stores, expecting the fields to populate correctly

**Screenshots**
![image](https://github.com/cmintey/wishlist/assets/51430659/aebe67fd-cc2f-4fdd-a355-c62b178f5335)

![image](https://github.com/cmintey/wishlist/assets/51430659/5ae997aa-ad55-4ee2-867c-e5bc56e5b0aa)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 121.01

**Smartphone (please complete the following information):**
 - Device: Google Pixel 8 Pro
 - OS: Android 14
 - Browser Firefox 121.01

**Additional context**
As mentioned in the description, I do not experience this bug on my phone.  I tried copying the link from the Amazon app and pasting it in and it worked.  Because that appeared to have been run through a url shortner, I also browsed to the same product and copied the url from the browser, then attempted to add it to wishlist; it worked as expected.

**Comment by cmintey** [comment]
Yeah unfortunately, Amazon doesn't like web scraping all that much, so sometimes if they can detect it, they will present a captcha, in which case, we can't do anything. I already have a retry in place that if we are presented with a captcha, we will retry and that fixes it sometimes, but in other cases it doesn't. 
I don't know that there is an easy workaround without making the scraper more complex, which I want to avoid. I will make it so that if we can't get by the captcha, the user will be presented with a message and no data will be filled into the form

**Comment by gearopolis** [comment]
That is a great work-around.  It is not surprising that Amazon would limit that functionality.  I was thinking about sharing this with the rest of the family and I think that could be a blocker for some of my less tech savvy family members.  Thanks again for sharing and the great work!

**Comment by gearopolis** [comment]
I just circled back around to this and it works as described.  Thanks!
